### HEALTCHECK
GET http://localhost:8000/healthcheck

### CREATE JOB REQUEST
POST http://localhost:8000/api/jobs
Content-Type: application/json

{
    "url": "https://www.elmundo.es/cronica/2025/07/21/687ab2dce9cf4a562e8b4570.html"
}

### GET JOB STATUS
GET http://localhost:8000/api/jobs/55e3e8fc-c823-4a27-8c1c-dd31705a7ac7/status

### GET JOB INFO
GET http://localhost:8000/api/jobs/55e3e8fc-c823-4a27-8c1c-dd31705a7ac7/completed