services:
  api:
    container_name: api
    build: .
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./src:/api:rw
    develop:
      watch:
        - path: ./requirements.txt
          action: rebuild
        - path: ./compose.yml
          action: rebuild
        - path: ./Dockerfile
          action: rebuild
    command: python3 main.py
  celery:
    container_name: celery
    build: .
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ./src:/api:rw
    develop:
      watch:
        - path: ./requirements.txt
          action: rebuild
        - path: ./compose.yml
          action: rebuild
        - path: ./Dockerfile
          action: rebuild
    command: celery -A worker.celery_app worker -l info
  db:
    container_name: db
    image: postgres:15
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: summaries
      TZ: UTC
    ports:
      - 5432:5432
  redis:
    container_name: redis
    image: redis:8
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

volumes:
  postgres-db:
    external: false
  redis-data:
    external: false
